use_frameworks!

platform :ios, '9.0'

target 'BlobPublicComponentDemo_Example' do
  pod 'BlobPublicComponentDemo', :path => '../'

  target 'BlobPublicComponentDemo_Tests' do
    inherit! :search_paths

    
  end
end
